name: fluent_window
description: "Custom Window for fluent_ui."
version: 0.1.8
homepage: https://github.com/4A6F6F6E61/fluent_window.git

environment:
  sdk: ^3.9.0
  flutter: ">=1.17.0"

dependencies:
  bitsdojo_window: ^0.1.6
  fluent_ui: ^4.12.0
  flutter:
    sdk: flutter
  flutter_acrylic: ^1.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
